/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/systems': typeof SystemsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/systems': typeof SystemsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/systems': typeof SystemsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/systems' | '/campaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/systems' | '/campaigns/$campaignId'
  id: '__root__' | '/' | '/systems' | '/campaigns/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemsRoute: typeof SystemsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemsRoute: SystemsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
