/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CampaignsCampaignIdEditRouteImport } from './routes/campaigns_.$campaignId.edit'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdEditRoute = CampaignsCampaignIdEditRouteImport.update({
  id: '/campaigns_/$campaignId/edit',
  path: '/campaigns/$campaignId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/systems': typeof SystemsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/systems': typeof SystemsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/systems': typeof SystemsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns_/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/systems'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/$campaignId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/systems'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/$campaignId/edit'
  id:
    | '__root__'
    | '/'
    | '/systems'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns_/$campaignId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemsRoute: typeof SystemsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsCampaignIdEditRoute: typeof CampaignsCampaignIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$campaignId/edit': {
      id: '/campaigns_/$campaignId/edit'
      path: '/campaigns/$campaignId/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemsRoute: SystemsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsCampaignIdEditRoute: CampaignsCampaignIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
